# Generated by Django 2.1 on 2018-08-22 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_type', models.CharField(max_length=64)),
                ('external_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=64)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_type', models.CharField(max_length=64)),
                ('external_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('view_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='baseuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mirrors.BaseUser'),
        ),
    ]
