# Generated by Django 2.1 on 2018-08-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0003_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=100)),
                ('is_buildin', models.BooleanField()),
                ('ext', models.TextField(null=True)),
                ('not_orderable', models.BooleanField(null=True)),
                ('poset_order', models.IntegerField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='options',
            unique_together={('type', 'code')},
        ),
    ]
