# Generated by Django 2.1 on 2018-08-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0005_auto_20180825_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mirrors.Team'),
        ),
    ]
