# Generated by Django 2.1 on 2018-08-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mirrors', '0006_auto_20180825_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='helloworld', to='mirrors.Team'),
        ),
    ]
